apiVersion: v1
kind: LimitRange
metadata:
 name: workshop
 namespace: template-test
spec:
 limits:
   - max:
       cpu: 750m
       memory: 750Mi
     default:
       cpu: 500m
       memory: 500Mi
     defaultRequest:
       cpu: 100m
       memory: 250Mi
     type: Container
